# Generated by Django 5.2.17 on 2026-08-21 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('password_hash', models.CharField(max_length=64, unique=True)),
                ('strength_score', models.IntegerField()),
                ('strength_label', models.CharField(max_length=16)),
                ('length', models.IntegerField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', '-created_at'], name='analyzer_pa_session_ea29a5_idx')],
            },
        ),
    ]
